<?php

namespace WorkflowBundle\Repository;

/**
 * workflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workflowRepository extends \Doctrine\ORM\EntityRepository
{
}
